Repository BAM-karaokebox/bkb-website-tests, pull requests merged in 2022-04, with the labels that each got.

#8 BAM-903,BAM-961 Improve the test-suite's resilience
  .gitignore
  playwright.config.ts
  tests/testClientPage.spec.ts
  tests/testHomeBam.spec.ts
  tests/testPlaylist.spec.ts
  tests/testVenues.spec.ts
Labels: echoes/effort: S, echoes/intent: throughput

#10 Bam 911 test as a backend user i get a notification as soon as a price is wrong
  .github/workflows/playwright.yml
  tests/testPrice.spec.ts
Labels: echoes/effort: S, echoes/intent: risk-mitigation

#9 BAM-978 add tag to every tests
  tests/testClientPage.spec.ts
  tests/testHomeBam.spec.ts
  tests/testPlaylist.spec.ts
  tests/testPrice.spec.ts
  tests/testVenues.spec.ts
Labels: echoes/effort: S, echoes/intent: throughput

#11 Bam 986 test as a backend user i get a notification as soon as a price is wrong
  .github/workflows/playwright.yml
  tests/testClientPage.spec.ts
  tests/testPrice.spec.ts
Labels: echoes/effort: S, echoes/intent: risk-mitigation, echoes/intent: throughput

#12 BAM-986 modify message format
  .github/workflows/playwright.yml
Labels: echoes/effort: S, echoes/intent: risk-mitigation

#13 BAM-986 Add trace on failure and remove unnecessary comments
  playwright.config.ts
Labels: echoes/effort: XS, echoes/intent: risk-mitigation
